default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: kainos
  password: shema
  pool: 5

development:
  <<: *default
  database: kainos_development

test:
  <<: *default
  database: kainos_test

production:
  <<: *default
  database: kainos_production
  username: kainos
  password: <%= ENV['KAINOS_DATABASE_PASSWORD'] %>
